### ISSUE TITLE
Python f-string support

### ISSUE THREAD

**Issue by alayamanas** [neoclide/coc-pairs#69] opened 2020-12-21 04:17 UTC
coc-pairs do not work in Python f-string,  
![20201221121627](https://user-images.githubusercontent.com/10472264/102738889-6723a500-4386-11eb-9b8e-21be52de1b31.png)

**Comment by chemzqm** [comment] 2020-12-21 04:26
Duplicate of #34

**Closed as completed by chemzqm** 2020-12-21 04:26 UTC
